scene:
  texture_dir: "assets/textures/background/natural/carpet"
  texture_scale_min: 1.0
  texture_scale_max: 2.0
  random_texture_rotation: true
  lighting:
    radius_min: 0.0 # Sharp shadows
    radius_max: 0.0
dataset:
  num_scenes: 1
  output_dir: "output/easy_office"
camera:
  samples_per_scene: 2
