dataset:
  output_dir: output/debug
  num_scenes: 1
camera:
  resolution:
  - 640
  - 480
  fov: 90.0
  samples_per_scene: 1
  min_distance: 1.0
  max_distance: 2.0
tag: {}
scenario:
  sampling_mode: random
  subject:
    type: TAGS
    tag_families:
    - tag36h11
    size_mm: 100.0
    tags_per_scene: 2
scene:
  lighting:
    intensity_min: 500
    intensity_max: 500
  background_hdri: null
  texture_dir: null
physics:
  scatter_radius: 0.5
renderer:
  mode: workbench
version: '0.2'
