dataset:
  num_scenes: 1
camera:
  resolution: [640, 480]
  fov: 120.0
  min_distance: 0.5
  max_distance: 1.5
tag:
  family: tag36h11
  size_mm: 100.0
scenario:
  sampling_mode: random
  subject:
    type: TAGS
    tag_families: [tag36h11]
    size_mm: 100.0
    tags_per_scene: 1
scene:
  background_hdri: null
physics:
  scatter_radius: 0.1
renderer:
  mode: workbench
version: '0.2'
