dataset:
  num_scenes: 1
camera:
  resolution: [640, 480]
  fov: 120.0
  min_distance: 0.5
  max_distance: 1.5
scenario:
  sampling_mode: random
  subject:
    type: BOARD
    rows: 4
    cols: 4
    marker_size_mm: 80.0
    square_size_mm: 100.0
    dictionary: tag36h11
scene:
  background_hdri: null
physics:
  scatter_radius: 0.1
renderer:
  mode: workbench
version: '0.2'
