import random

class SeedManager:
    """Manages deterministic seed generation hierarchy."""
    
    def __init__(self, master_seed: int):
        self.master_seed = master_seed
        
    def get_shard_seed(self, shard_index: int) -> int:
        """Get a deterministic seed for a specific shard index.
        
        This implements the 'Sequential Sequence' strategy:
        Shard N receives the N-th seed generated by a PRNG initialized with the Master Seed.
        """
        # Initialize a new isolated RNG with the master seed
        rng = random.Random(self.master_seed)
        
        # Generate the N-th seed (0-indexed)
        # We discard the first 'shard_index' values
        seed = 0
        for _ in range(shard_index + 1):
            seed = rng.randint(0, 2**32 - 1)
            
        return seed
