dataset:
  output_dir: output/aruco_cb_v2
  num_scenes: 1

camera:
  resolution: [1280, 1280]
  samples_per_scene: 1
  min_distance: 1.2
  max_distance: 1.5
  min_elevation: 0.8
  max_elevation: 0.9

tag:
  size_meters: 0.1

scenario:
  layout: cb
  tag_families: [DICT_6X6_250]
  grid_size: [6, 6]
  corner_size: 0.02
  tag_spacing_bits: 2
  sampling_mode: random
